### ISSUE TITLE
Add a Copy Button to Password and Generated Hash using Clipboard.js

### ISSUE THREAD

**Issue by gayankalhara** [flincube/password-hash-generator#23]

**Comment by objNameGit** [comment]
Hello. Can I try to do this?

**Comment by gayankalhara** [comment]
Hi! The issue was already resolved in #24. However, the copy button is pretty basic. It's not in the preferred style we expect. We were looking for something like this as seen on the Clipboard.js example.

![image](https://user-images.githubusercontent.com/8076584/66084524-799c9d80-e58c-11e9-8f1e-ec44d7d2ff3e.png)

If you can give it a try that would be great.
